import styled from "styled-components";
import Head from "next/head";
import SectionContainer from "@/component/SectionContainer";
import TopSection from "@/component/TopSection";
import { useState, useEffect, useRef } from "react";
import Image from "next/image";

const API_KEY = "10923b261ba94d897ac6b81148314a3f";

interface JsonProps {
  [key: string]: string | number;
}

export const Paging = () => {
  const [data, setData] = useState<JsonProps[]>([]);
  const target = useRef<any>(null);

  //useEffect 렌더링 문제 비구조할당 스프래드 연산자 얕은복사 깊은복사
  const dataFetch = async () => {
    console.log(11);
    const { results } = await (
      await fetch(
        `https://api.themoviedb.org/3/movie/popular?api_key=${API_KEY}`
      )
    ).json();

    setData((prev) => [...prev, ...results]);
  };

  useEffect(() => {
    dataFetch();
  }, []);

  useEffect(() => {
    console.log(data);
    if (data) {
      // data가 존재하면
      const observer = new IntersectionObserver((entries) => {
        if (entries[0].isIntersecting) {
          dataFetch();
        }
      });

      // 옵져버 탐색 시작
      if (target.current) {
        observer.observe(target.current);
      }
      return () =>
        // 옵져버 중지

        observer && observer.disconnect();
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>Intersection-Observer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <TopSection skill={[]} description={[]} status={"개발예정"} />
        <SectionContainer>
          <Container>
            {data && data.length > 0
              ? data.map((movie: JsonProps, index: number) => {
                  return (
                    <div key={movie.id}>
                      <ImageBox>
                        <Image
                          src={`https://image.tmdb.org/t/p/w500/${movie.poster_path}`}
                          alt="image"
                          loading="lazy"
                          unoptimized={true}
                          layout="fill"
                          style={{}}
                        />
                        {/* ref={index === 10 ? target : null} */}
                        <Title ref={index === 19 ? target : null}>
                          {movie.original_title}
                        </Title>
                      </ImageBox>
                    </div>
                  );
                })
              : null}
          </Container>
        </SectionContainer>
      </Wrapper>
    </>
  );
};

export default Paging;

const Wrapper = styled.section`
  position: relative;
  height: 100%;
`;

// export async function getServerSideProps(context: any) {
//   const { results } = await (
//     await fetch(`https://localhost:3000/api/movies`)
//   ).json();
//   return {
//     props: {
//       results,
//     },
//   };
// }

const Container = styled.div`
  position: relative;
  display: flex;
  flex-wrap: wrap;
  width: 100%;
  height: 100%;
  overflow-y: scroll;
  justify-content: center;
  align-items: center;
  ::-webkit-scrollbar {
    display: none;
  }
`;

const Title = styled.div`
  position: absolute;
  bottom: -30px;
  font-size: 12px;
`;

const ImageBox = styled.div`
  position: relative;
  width: 200px;
  height: 200px;
  margin: 0 20px 50px;
`;
