import Head from "next/head";
import TopSection from "@/component/TopSection";
import styled from "styled-components";
import { Map, MapMarker } from "react-kakao-maps-sdk";
import { useState } from "react";

export const KakaoMapApi = () => {
  const [position, setPosition] = useState({ lat: 0, lng: 0 });
  return (
    <>
      <Head>
        <title>Kakao-Map-Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <TopSection
          skill={["Kakao-Map-Api"]}
          description={"카카오 맵"}
          status={"개발완료"}
        />
        <Container>
          <Map // 지도를 표시할 Container
            center={{
              // 지도의 중심좌표
              lat: 37.566826,
              lng: 126.9786567,
            }}
            style={{
              width: "100%",
              height: "550px",
            }}
            level={3} // 지도의 확대 레벨
            onClick={(_t, mouseEvent) =>
              setPosition({
                lat: mouseEvent.latLng.getLat(),
                lng: mouseEvent.latLng.getLng(),
              })
            }
          >
            {position && <MapMarker position={position} />}
          </Map>
          {position && (
            <p>
              {"클릭한 위치의 위도는 " +
                position.lat +
                " 이고, 경도는 " +
                position.lng +
                " 입니다"}
            </p>
          )}
        </Container>
      </Wrapper>
    </>
  );
};

export default KakaoMapApi;

const Wrapper = styled.section`
  position: relative;
  height: 100%;
`;
const Container = styled.div`
  position: relative;
  height: calc(75% - 25px);
  margin: 24px 0 0 0;
  padding: 25px;
  background-color: transparent;
  border-radius: 16px;
  box-sizing: border-box;
  box-shadow: 4px 6px 24px 6px rgb(0 0 0 / 20%);
`;
