import Head from "next/head";
import TopSection from "@/component/TopSection";
import styled from "styled-components";
import SectionContainer from "@/component/SectionContainer";

export const Loading = () => {
  return (
    <>
      <Head>
        <title>Loading-Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <TopSection
          skill={["CSS"]}
          description={["Loading"]}
          status={"개발완료"}
        />
        <SectionContainer>
          <Spinner></Spinner>
        </SectionContainer>
      </Wrapper>
    </>
  );
};

export default Loading;

const Wrapper = styled.section`
  position: relative;
  height: 100%;
`;

const Spinner = styled.div`
  position: absolute;
  top: 50%;
  left: 50%;
  /* margin: 0 auto; */
  width: 160px;
  height: 160px;
  border: 24px solid rgba(255, 165, 0, 0.4);
  border-top: 24px solid rgba(255, 165, 0, 1);
  border-radius: 50%;
  animation: spin 2s linear infinite;
  @keyframes spin {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
`;
