import Head from "next/head";
import TopSection from "@/component/TopSection";
import styled from "styled-components";
import SectionContainer from "@/component/SectionContainer";
import LoadingComponent from "@/component/LoadingComponent";

export const Loading = () => {
  return (
    <>
      <Head>
        <title>Loading-Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <TopSection
          skill={["CSS"]}
          description={["Loading"]}
          status={"개발완료"}
        />
        <SectionContainer>
          <LoadingComponent />
        </SectionContainer>
      </Wrapper>
    </>
  );
};

export default Loading;

const Wrapper = styled.section`
  position: relative;
  height: 100%;
`;
